<nav>
    <ul id="navbar">
        <li><a href ="index.php" class ="menu">HOME</a></li>
        <li><a href ="product.php" class ="menu">PRODUCT</a></li>
        <li><a href ="enquire.php" class ="menu">ENQUIRY</a></li>
        <li><a href ="manager.php" class ="menu">MANAGER</a></li>
        <li><a href ="about.php" class ="menu">ABOUT</a></li>
        <li><a href ="enhancements.php" class ="menu">ENHANCEMENT1</a></li>
        <li><a href ="enhancements2.php" class ="menu">ENHANCEMENT2</a></li>
        <li><a href ="enhancements3.php" class ="menu">ENHANCEMENT3</a></li>
    </ul>
</nav>
